# Generated by Django 4.2.6 on 2023-10-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='addresse',
            new_name='address',
        ),
    ]
